# Generated by Django 2.1.2 on 2018-10-19 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_answer', models.CharField(max_length=100, unique=True)),
                ('answer_1', models.CharField(max_length=100)),
                ('answer_2', models.CharField(max_length=100)),
                ('answer_3', models.CharField(max_length=100)),
                ('answer_4', models.CharField(max_length=100)),
                ('answer_5', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AnswerV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('var_answer', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='guestionNum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_num', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='resultData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_ok', models.CharField(max_length=100, null=True)),
                ('answer_no', models.CharField(max_length=100, null=True)),
                ('result', models.CharField(max_length=100, null=True)),
                ('success', models.NullBooleanField(default=False)),
                ('status', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('name_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='timeOut_answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeOut_answer', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_ok',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.AnswerV'),
        ),
    ]
