# Generated by Django 2.1.2 on 2018-10-19 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='correctValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameModel(
            old_name='Article',
            new_name='Question',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='answer_1',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='answer_2',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='answer_3',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='answer_4',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='answer_5',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='answer_ok',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='question_answer',
        ),
        migrations.AddField(
            model_name='answer',
            name='answer',
            field=models.CharField(default=0, max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='quiz.Question', unique=True),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AnswerV',
        ),
        migrations.AddField(
            model_name='answer',
            name='correct_or_not',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='quiz.correctValue'),
            preserve_default=False,
        ),
    ]
