# Generated by Django 2.1.2 on 2018-10-19 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20181019_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correctvalue',
            name='value',
            field=models.CharField(default='Нет', max_length=5, verbose_name='Правильность ответа'),
        ),
    ]
