# Generated by Django 2.1 on 2018-10-19 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20181019_1901'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='guestionNum',
            new_name='questionNumber',
        ),
        migrations.AddField(
            model_name='question',
            name='answer_order',
            field=models.CharField(blank=True, choices=[('content', 'Content'), ('random', 'Random'), ('none', 'None')], help_text='Правило по которому будутпоказаны ответы пользователюрандомно, по контенту или none', max_length=30, null=True, verbose_name='Правило вывода ответов'),
        ),
    ]
