# Generated by Django 2.1 on 2018-10-19 16:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20181019_2159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Название теста')),
                ('description', models.TextField(blank=True, help_text='Описание теста', verbose_name='Описание теста')),
                ('url', models.SlugField(help_text='user friendly url', max_length=60, verbose_name='user friendly url')),
                ('random_order', models.BooleanField(default=True, help_text='Показывает вопросы в случайной последовательности', verbose_name='Рандомная последовательность выдачи вопросов')),
                ('max_questions', models.PositiveIntegerField(blank=True, help_text='Максимальное кол-во вопросов на каждую попытку сдачи теста', null=True, verbose_name='Максимальное кол-во вопросов')),
                ('answers_at_end', models.BooleanField(default=False, help_text='Правильный ответ на вопрос не будет показан после ответа пользователя', verbose_name='Правильный ответ в конце')),
                ('exam_paper', models.BooleanField(default=False, help_text='Если да, то результат каждой попытки будет сохраняться. Необходимо для маркировки.', verbose_name='Результат теста')),
                ('single_attempt', models.BooleanField(default=False, help_text='Если да, то будет разрешена только одна попыткаНезарегиситрированные пользователи не смогут сдать экзамен.', verbose_name='Количество попыток')),
                ('pass_mark', models.SmallIntegerField(blank=True, default=0, help_text='Процент необходимый для сдачи теста', validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Порог прохождения теста')),
                ('success_text', models.TextField(blank=True, help_text='Показывает тект если пользователь сдал тест.', verbose_name='Текст Сдал')),
                ('fail_text', models.TextField(blank=True, help_text='Показывает если пользователь не сдал тест.', verbose_name='Текст Провал')),
                ('draft', models.BooleanField(blank=True, default=False, help_text='Если да, то тест будет виден только админам.', verbose_name='В процессе разработки')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizzes',
            },
        ),
    ]
