# Generated by Django 2.1.2 on 2018-10-25 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_auto_20181021_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, help_text='Объяснение будет показано после ответа на вопрос.', max_length=2000, verbose_name='Объяснение'),
        ),
    ]
