# Generated by Django 2.1.2 on 2018-12-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_auto_20181205_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Департамент/Служба/Отдел'),
        ),
        migrations.AlterField(
            model_name='filial',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Филиал'),
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Город/Село'),
        ),
    ]
