# Generated by Django 2.1.2 on 2018-12-06 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_auto_20181206_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='filial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Filial', verbose_name='Филиал'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Position', verbose_name='Должность'),
        ),
    ]
