# Generated by Django 2.1.4 on 2018-12-23 10:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_auto_20181206_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='department',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='quiz.Filial', verbose_name='Департамент/Служба/Отдел'),
            preserve_default=False,
        ),
    ]
