# Generated by Django 2.1.4 on 2018-12-23 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0021_auto_20181223_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='department_article_set', to='quiz.Department', verbose_name='Департамент/Служба/Отдел'),
        ),
    ]
