# Generated by Django 2.1.4 on 2018-12-30 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0023_auto_20181223_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='attempt_choise',
            field=models.CharField(choices=[('D', 'Одна попытка в день'), ('W', 'Одна попытка в неделю'), ('M', 'Одна попытка в месяц'), ('Y', 'Одна попытка в год'), ('U', 'Неограниченные попытки')], default='U', max_length=50),
        ),
    ]
