# Generated by Django 2.1.4 on 2019-01-02 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0025_auto_20181231_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='pic_folder/None/no-img.png', upload_to='pic_folder/'),
        ),
    ]
