# Generated by Django 2.1.4 on 2019-01-02 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0026_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='quiz/static/quiz/images/no-img.png', upload_to='quiz/static/quiz/images/'),
        ),
    ]
