# Generated by Django 2.1.4 on 2019-01-03 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0027_auto_20190102_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='/static/quiz/images/no-img.png', upload_to='quiz/static/quiz/images/'),
        ),
    ]
