# Generated by Django 2.1.4 on 2019-01-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0028_auto_20190103_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='static/images/no-img.png', upload_to='static/images/'),
        ),
    ]
