# Generated by Django 2.1.4 on 2019-01-05 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0029_auto_20190103_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='profile_images/no-img.png', upload_to='profile_images/'),
        ),
    ]
