# Generated by Django 2.1.4 on 2019-01-10 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0030_auto_20190105_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='filial',
            field=models.ForeignKey(blank=True, help_text='Выберите филиал, для которого будет доступен тест', null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Filial', verbose_name='Филиал'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Выберите категорию теста', null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Category', verbose_name='Категория'),
        ),
    ]
