# Generated by Django 2.1.4 on 2019-01-10 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0031_auto_20190110_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='filial',
            field=models.ForeignKey(blank=True, default='Все', help_text='Выберите филиал, для которого будет доступен тест', null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Filial', verbose_name='Филиал'),
        ),
    ]
